Feature: Display Charts Visualizing Event Details

 Scenario: Scenario description 
  Given ... 
  And ... 
  When ... 
  Then …

 Scenario: Scenario description 
  Given ... 
  When ... 
  Then … 
  And ... 